### ISSUE TITLE
Error with "page.style._resetCssValues" since NativeScript 3.0 

### ISSUE THREAD

**Issue by jet-lee-m** [NathanaelA/nativescript-orientation#17]
Hi,

I have following error since nativescript 3.0 update. 

`file:///app/tns_modules/nativescript-orientation/orientation.js:302:28: JS ERROR TypeError: page.style._resetCssValues is not a function. (In 'page.style._resetCssValues()', 'page.style._resetCssValues' is undefined)`

My solution is to comment this row in orientation.js.  

Can you fix this or remove it in your next commit?

Thx.

**Comment by NathanaelA** [comment]
I have a pull request that might fix the issues; I just haven't had time to test it.

**Comment by demetrio812** [comment]
Hello...Any luck with integrating this? thanks

**Comment by tscislo** [comment]
same here

**Comment by MemoRodMx** [comment]
same :S

**Comment by mm-ns** [comment]
same :/ no news?

**Comment by NathanaelA** [comment]
My apologies guys & gals -- I have been focused on getting the new plugins site released (which is done: https://plugins.nativescript.rocks), that I haven't had the time to go through all my plugins.    I plan on going thru all my plugins in late Sept and making sure they ALL work in 3.0.

**Comment by rgoede** [comment]
Please leave a statement in the README that it doesn't work on nativescript 3. That would have saved me a lot of time and frustration.

**Comment by NathanaelA** [comment]
@rgoede - I apologize for your wasting time and frustration, but right now there are a lot of plugins that don't support 3.0, adding a readme change to all my plugins that don't support 3.0 is going to *waste* a lot of my time.   The best way to know if a plugin supports 3.0 is look on my plugins page listed above...   ;-)

**Comment by rgoede** [comment]
Not to whine or something, but on https://plugins.nativescript.rocks/plugin/nativescript-orientation it states: 
TNS Version: | 2.x & 3.x

**Comment by NathanaelA** [comment]
Nice, thanks for letting me know.  ;-)   I'll track down why it thinks this plugin is 3.0 compatible...  It shouldn't be thinking it is...

**Comment by NathanaelA** [comment]
@rgoede; thanks for letting me know.  The data I collected was correct, but my display routine on the site had a typo in it that caused it to always display 2.x and 3.x compatible.     It is now fixed.  ;-)

**Comment by OPADA-Eng** [comment]
any news for this ?

**Comment by elvismercado** [comment]
Any ETA on fixing this?

**Comment by elvismercado** [comment]
Great will be waiting for it

**Comment by NathanaelA** [comment]
This is fixed in the newest version!   Yay.
