### ISSUE TITLE
Nativescript 3.0 rc: "page.style._resetCssValues()" is not a function

### ISSUE THREAD

**Issue by andy-tai** [NathanaelA/nativescript-orientation#9]
I have a Nativescript 2.5 / Angular project that uses nativescript-orientation that works fine.  When upgrading to Nativescript 3.0 rc following the instruction in https://www.nativescript.org/blog/nativescript-3.0-release-candidate-available-today, the app fails to run with the error message  

 "page.style._resetCssValues()" is not a function

probably the new Nativescript internal interface changed, so the plugin needs updating to work with Nativescript 3.0

**Comment by NathanaelA** [comment]
Thank you for your bug report; and yes the **vast majority** of ALL the plugins by everyone will need to be upgraded to work with NS 3.0.     3.0 is a fairly radical change for most plugins.

**Comment by ignaciolarranaga** [comment]
Hey guys, experienced the same problem (just migrated to 3.0). Is there some update/fix/workaround ?

**Comment by NathanaelA** [comment]
@ignaciolarranaga - No, this plugin has not been upgraded yet to work in 3.0...   When it is finally upgraded, the main page will list which version is compatible with v2.5 and which version is compatible with 3.0...

**Comment by prolink007** [comment]
#13 I submitted a PR to fix this issue. It appears `refreshCss` calls `resetCssValues` now.

**Comment by DimitarTachev** [comment]
Full NativeScript 3.0 support PR is available [here.](https://github.com/NathanaelA/nativescript-orientation/pull/14)

**Comment by NathanaelA** [comment]
This is now fixed in the latest version.
